<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Converter</title>

    <!-- Styles -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <style>
        #last-results {
            resize: none;
            overflow:hidden;
            margin-bottom: 10px;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <!-- Branding Image -->
            <a class="navbar-brand" href="#">
                Converter
            </a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-9">
                            <label class="control-label">last results:</label>
                            <textarea class="form-control" id="last-results" rows="5" readonly></textarea>
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Result:</label>
                            <input class="form-control" type="number" readonly id="result">
                        </div>
                    </div>
                    <div class="row top-margin">
                        <div class="col-md-3">
                            <input class="form-control" type="number" id="value" placeholder="Value">
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon">From:</span>
                                <select class="form-control" id="from">
                                    <?php foreach ($this->currencies as $currency): ?>
                                        <option value="<?php echo $this->escape($currency->id) ?>">
                                            <?php echo $this->escape($currency->name) ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon">To:</span>
                                <select class="form-control" id="to">
                                    <?php foreach ($this->currencies as $currency): ?>
                                        <option value="<?php echo $this->escape($currency->id) ?>">
                                            <?php echo $this->escape($currency->name) ?>
                                        </option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-info start-convert">Convert!</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/js/app.js"></script>

</body>
</html>
